language: go

os: linux
dist: trusty
sudo: false

go:
  - 1.11
  - tip

env:
  - GO111MODULE=on DEP_VERSION="X.X.X"

before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - go get github.com/magefile/mage
  - go get github.com/mattn/goveralls

install:
  - mage -v deps

script:
  - mage -v vet
  - mage -v testCoverage

after_script:
  - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken=$COVERALLS_TOKEN

matrix:
  allow_failures:
    - go: 'tip'
